package:
  name: distributed
  version: "1.8.1"

source:
  path: ../

requirements:
  build:
    - python
    - tornado
    - toolz
    - cloudpickle
    - dask
    - click
    - boto3
    - locket
    - six
    - tblib

  run:
    - python
    - tornado
    - toolz
    - cloudpickle
    - dask
    - click
    - boto3
    - locket
    - six
    - tblib

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.diagnostics
    - distributed.http

about:
  home: http://distributed.readthedocs.org/en/latest/
  license: BSD
  summary: 'Distributed computing'
